### ISSUE TITLE
"total" shows the total records in the table instead of the total records returned after "where" clause

### ISSUE THREAD

**Issue by soubhikchatterjee** [eclass/sequelize-paginate#10]
Please consider the code below:

```
const options = {
            page: req.query.page || 1,
            paginate: 10,
            order: [['id', 'DESC']],
            where: { course_id:  2}
        }

        const { docs, pages, total } = await studentModel.paginate(options)
```

When I console log **total**, it returns **90**, instead it should return the record count **25** which is the count after i apply the _where_ clause.

Is it a bug? How do I fix this?

**Comment by lgaticaq** [comment]
Hi @soubhikchatterjee. I make a new test and works fine. Check in [test.js](https://github.com/eclass/sequelize-paginate/blob/master/test/index.js#L101-L109) and [travis](https://travis-ci.org/eclass/sequelize-paginate/jobs/501503414#L481).

**Comment by soubhikchatterjee** [comment]
Hello @lgaticaq 

Thanks for your reply.

In your test case, the **docs.length** is equal to **total**.  This test case will always pass.

Could you please write a test case where the filtered result is less than the total records available in the db table?

Thanks

**Comment by lgaticaq** [comment]
Test updated

```js
it('should paginate with filters, order and paginate', async () => {
  const { docs, pages, total } = await Author.paginate({
    order: [['name', 'DESC']],
    where: { name: { [Sequelize.Op.like]: 'author1%' } },
    paginate: 5
  })
  expect(docs).to.be.an('array')
  expect(docs.length).to.equal(5)
  expect(pages).to.equal(3)
  expect(total).to.equal(11)
})
```

**Comment by soubhikchatterjee** [comment]
Shouldn't the total also reflect the same number as docs.length i.e. 5?

**Comment by lgaticaq** [comment]
**total** is the total of query data. **docs.length** is the amount of register for this page (page 1) paginate by 5. The example query have 3 pages. Page 1 and 2 contains 5 elements. And page 3 contains 1 element. The total is 11 elements.

**Comment by soubhikchatterjee** [comment]
Okay, and how many records are there in the DB?

**Comment by lgaticaq** [comment]
99 records

**Comment by lgaticaq** [comment]
@soubhikchatterjee any other questions?

**Comment by soubhikchatterjee** [comment]
Thanks @lgaticaq
