### ISSUE TITLE
Doesn't factor in grouping / relations

### ISSUE THREAD

**Issue by antony** [eclass/sequelize-paginate#2]
If I have a grouping/relations clause in my SQL, the pagination shows a total based on raw rows fetched, not final items returned.

It looks like the count doesn't factor in the grouping clauses that are made by Sequelize in this instance.

so if I have 10 events each with 3 different dates assigned to them, for example:

```js
const { Availability } = connection.models
  return {
    model: Availability,
    as: 'availability'
  }
```

I end up with 30 total and 3 pages of 10, rather than 10 total and 1 page.

**Comment by antony** [comment]
Turns out this isn't really possible with one to many! Back to the drawing board.

**Comment by broodfusion** [comment]
I'm having this issue as well with trying to include a one-to-many relationship.
For example, say I have defined one Author - many Books.
when I do
```
return Author.paginate({
      include: [
        {
          model: Book,
          attributes: ['Title', 'Description'],
          where: // where object here
        }
      ],
      attributes: ['Name'],
      page: req.query.page,
      limit: 25,
      order: [['id', 'DESC']],
      where: // where object here
    })
      .then(...)
```
It doesn't return the correct # of pages. Say in this case the returned `pages` = 100,
But when I actually go to `/api/author?page=100`, it will either error out or return empty.

**Comment by broodfusion** [comment]
> Turns out this isn't really possible with one to many! Back to the drawing board.

Hi @antony did you ever figure this out? I'm having a similar issue when including a 1-many relationship. Please details here: https://github.com/eclass/sequelize-paginate/issues/3

Thanks!
