### ISSUE TITLE
problem when including a one-to-many relationship.

### ISSUE THREAD

**Issue by broodfusion** [eclass/sequelize-paginate#3]
For example, say I have defined one Author - many Books.
when I do
```
return Author.paginate({
      include: [
        {
          model: Book,
          attributes: ['Title', 'Description'],
          where: // where object here
        }
      ],
      attributes: ['id', 'Name'],
      page: req.query.page,
      paginate: 25,
      order: [['id', 'DESC']],
      where: // where object here
    })
      .then(...)
```
It doesn't return the correct # of pages. Say in this case the returned `pages` = 100,
But when I actually go to `/api/author?page=100`, it will either error out or return empty.

_Originally posted by @broodfusion in https://github.com/_render_node/MDEyOklzc3VlQ29tbWVudDQ0MzA5ODg5OQ==/timeline/issue_comment#issuecomment-443098899_

**Comment by lgaticaq** [comment]
@broodfusion check the new version v1.1.4 and show the [test](https://github.com/eclass/sequelize-paginate/blob/master/test/index.js#L79-L90)

**Comment by broodfusion** [comment]
thanks I figured it out using with just sequelize...had to add `subQuery: false` and specify a value for `col`.
