### ISSUE TITLE
Fails to acknowledge scope

### ISSUE THREAD

**Issue by dsmackie** [eclass/sequelize-paginate#46]
Pagination is forced to the default model. Any attempt to scope prior to pagination is ignored.

See PR #45

**Comment by lgaticaq** [comment]
Hi. Can you indicate an example where an error occurs with what you indicate please

**Comment by dsmackie** [comment]
```
models.User.addScope('deleted', {
  where: {
    delete: true
  }
}

let result = models.User.scope('deleted').paginate();
```
The `result` will contain all users as the paginate function ignores the assigned scope since it is called on the parent model instead of the scoped instance.
